import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import MyNav from '@/components/MyNav'
import 'bootstrap/dist/css/bootstrap.min.css' // Import bootstrap CSS
import Hero from '@/components/Hero'
import Testimonials from '@/components/Testimonials'
import NavWithHero from '@/components/NavWithHero'
import Footer from '@/components/Footer'

export default function Home() {
  return (
    <>
      <Head>
        <title>Classy Cutz</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main className='bg'>
        <NavWithHero />
        <Hero />
        <Testimonials />

        <Footer />
      </main>
    </>
  )
}
