import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import MyNav from '@/components/MyNav'
import 'bootstrap/dist/css/bootstrap.min.css' // Import bootstrap CSS
import Hero from '@/components/Hero'
import Testimonials from '@/components/Testimonials'
import NavWithHero from '@/components/NavWithHero'
import Footer from '@/components/Footer'
import { loadUser } from '@/lib/loadUser'
import type { InferGetStaticPropsType, GetStaticProps } from 'next'
import { useDispatch, useSelector } from 'react-redux'
import { useEffect } from 'react'
import { useRouter } from 'next/router'
import { Layout } from '@/components/Layout'

export default function Home() {
  const User = useSelector((state: any) => state.User)
  const loggedIn = useSelector((state: any) => state.isLoggedIn)

  return (
    <>
      <Head>
        <title>Classy Cutz</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main className=''>
        {/* <NavWithHero User={User} loggedIn={loggedIn} />
        <Hero /> */}
        <Hero />
        <Testimonials />

        {/* <Footer /> */}
      </main>
    </>
  )
}
// export const getServerSideProps = wrapper.getServerSideProps(
//   (store) =>
//     async ({ params }) => {
//       // we can set the initial state from here
//       // we are setting to false but you can run your custom logic here
//       const dispatcher = useDispatch()
//       await store.dispatch(UserAction.setUser({}))
//       console.log('State on server', store.getState())
//       return {
//         props: {
//           user: false,
//         },
//       }
//     }
// )
